name: Bug report 
description: Create a bug report for SuperCoder.
labels: ['status: needs triage']
body:
  - type: markdown
    attributes:
      value: |
        ### ⚠️ Issue Creation Guideline
        * Join our [discord](https://discord.gg/dXbRe5BHJC) to discuss what's going on
        * If you need help, you can ask in the [#general-discussion](https://discord.com/channels/1107593006032355359/1257985438627663924) section or in [#supercoder-support](https://discord.com/channels/1107593006032355359/1256153481387970632)
        * **Thoroughly search the [existing issues](https://github.com/TransformerOptimus/SuperCoder/issues) before creating a new one**

  - type: checkboxes
    attributes:
      label: ⚠️ Check for existing issues before proceeding. ⚠️
      description: >
        Please [search the history](https://github.com/TransformerOptimus/SuperCoder/issues)
        to see if an issue already exists for the same problem.
      options:
        - label: I have searched the existing issues, and there is no existing issue for my problem
          required: true

  - type: markdown
    attributes:
      value: |
        Please confirm that the issue you have is described well and precise in the title above ⬆️.
        Think like this: What would you type if you were searching for the issue?
        
        For example:
        ❌ - SuperCoder workbench server shows 503 error. 
        ✅ - Even after story is executed completely and moved to "Done" stage, SuperCoder workbench server shows 503 error.
        
        Please help us help you by following these steps:
        - Search for existing issues, adding a comment when you have the same or similar issue is tidier than "new issue" and 
          newer issues will not be reviewed earlier, this is dependent on the current priorities set by our wonderful team
        - Ask on our Discord if your issue is known when you are unsure (https://discord.gg/dXbRe5BHJC)
        - Provide relevant info:
          - Provide Docker Logs(docker compose logs) and workbench ID (looks like "be-oqajm-24ec535d-eb35-4099-91c2-6fb7415337dd") whenever possible.
          - If it's a pip/packages issue, mention this in the title and provide pip version, python version.
          - Check network tab and provide any screenshot if you see a failing request with your issue.
  - type: dropdown
    attributes:
      label: Where are you using SuperCoder?
      description: >
        Please select the operating system you were using to run SuperCoder when this problem occurred.
      options:
        - Windows
        - Linux
        - MacOS
        - Codespaces
        - Cloud
        - Other
    validations:
      required: true
      nested_fields:
        - type: text
          attributes:
            label: Specify the system
            description: Please specify the system you are working on.

  - type: dropdown
    attributes:
      label: Which branch of SuperCoder are you using?
      description: |
        Please select which version of SuperCoder you were using when this issue occurred.
        If installed with git you can run `git branch` to see which version of SuperCoder you are running.
      options:
        - Main
        - Cloud Version
        - Other
    validations:
      required: true


  - type: dropdown
    attributes:
      label: Which area covers your issue best?
      description: >
        Select the area related to the issue you are reporting.
      options:
        - Installation and setup
        - Front-End Board
        - Front-End Workbench
        - Back-End Board 
        - Back-End Workbench
        - Code Editor
        - Pull Request
        - Settings
        - Other
    validations:
      required: true
      autolabels: true
      nested_fields:
        - type: text
          attributes:
            label: Specify the area
            description: Please specify the area you think is best related to the issue.

  - type: textarea
    attributes:
      label: Describe your issue.
      description: Describe the problem you are experiencing. Try to describe only the issue and phrase it short but clear. ⚠️ Provide NO other data in this field  
    validations:
      required: true

  - type: textarea
    attributes:
     label: How to replicate your Issue?
     description: |
      Always Mention Project Name, Workbench ID.
      For Back-End Story mention - Story Summary, Description, Test Cases and Dev instructions.
      Provide any other data which might be relevant for us to replicate this issue.
      ⚠️ Provide NO other data in this field  
    validations:
     required: false

  - type: markdown
    attributes:
      value: |
        ⚠️ Please keep in mind that the log files may contain personal information such as credentials. Make sure you hide them before copy/pasting it! ⚠️        
  - type: input
    attributes:
      label: Upload Error Log Content
      description: |
        Upload the error log content, this can help us understand the issue better. 
        To do this, you can simply copy the logs from the terminal with which you did 'docker compose up' or in a new terminal, 
        enter 'docker compose logs' and copy/paste the error contents to this field. 
        If you're using the cloud version, add network tab details or any traceback error if applicable. if no error log present, write N/A.
        ⚠️ The activity log may contain personal data given to SuperCoder by you in prompt or input as well as 
        any personal information that SuperCoder collected out of files during last run. Please hide them before sharing. ⚠️
    validations:
      required: true
