name: Build IDE image

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'The ide to build'
        options:
          - python
          - node

concurrency:
  group: build-ide-image
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ./ide/${{ github.event.inputs.environment }}
          push: true
          tags: superagidev/supercoder-${{ github.event.inputs.environment }}-ide:latest